FROM node:22-alpine

WORKDIR /app

# create user for security
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

# switch to non-root user
USER appuser

EXPOSE 5000

CMD ["node", "src/server.js"]